-- 0002 — media library
--
-- Metadata only. File bytes live in Google Cloud Storage; this table holds facts ABOUT
-- files so the database stays small, backups stay fast, and the CDN can serve the objects.

create table if not exists public.media (
  id                uuid primary key default gen_random_uuid(),

  -- Object path inside the bucket. Generated by the server from the content hash, never
  -- from the uploader's filename, which is a path traversal waiting to happen.
  storage_path      text not null unique,

  -- Which half of the bucket this lives in. Public objects are CDN-served; private ones
  -- are reachable only through a short-lived signed URL. The resume is private because it
  -- is personal data.
  visibility        text not null default 'public'
                    check (visibility in ('public', 'private')),

  -- A stable name the site can look a file up by, so replacing the resume does not change
  -- the URL anything links to. Null for ordinary library items.
  slug              text unique,

  original_filename text not null,
  mime_type         text not null,
  original_bytes    integer not null,
  stored_bytes      integer not null,

  -- Deduplication key. The same file uploaded twice is stored once.
  sha256            text not null,

  width             integer,
  height            integer,
  alt_text          text,

  -- Supabase auth user id. The stable identity key, not an email address, which changes.
  uploaded_by       uuid not null references auth.users (id),

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create unique index if not exists idx_media_sha_visibility
  on public.media (sha256, visibility);
create index if not exists idx_media_created_at on public.media (created_at desc);
create index if not exists idx_media_visibility on public.media (visibility);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists media_touch_updated_at on public.media;
create trigger media_touch_updated_at
  before update on public.media
  for each row execute function public.touch_updated_at();

alter table public.media enable row level security;

-- The public may read the row for a PUBLIC object only. A private row is never exposed
-- through the anon key, so a visitor cannot even learn that the resume object exists,
-- let alone its path.
--
-- Every write is restricted to an authenticated user. There is exactly one account, so
-- this is the whole authorization model: no roles, because a role system for one user has
-- nothing to say.
do $$
begin
  if not exists (select 1 from pg_policies where tablename='media' and policyname='media_public_read') then
    create policy media_public_read on public.media
      for select to anon using (visibility = 'public');
  end if;

  if not exists (select 1 from pg_policies where tablename='media' and policyname='media_owner_read') then
    create policy media_owner_read on public.media
      for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where tablename='media' and policyname='media_owner_insert') then
    create policy media_owner_insert on public.media
      for insert to authenticated with check (uploaded_by = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where tablename='media' and policyname='media_owner_update') then
    create policy media_owner_update on public.media
      for update to authenticated using (uploaded_by = auth.uid()) with check (uploaded_by = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where tablename='media' and policyname='media_owner_delete') then
    create policy media_owner_delete on public.media
      for delete to authenticated using (uploaded_by = auth.uid());
  end if;
end $$;
